"""Start shared monitoring and register successfully started local model packs."""

from __future__ import annotations

import fcntl
import os
from pathlib import Path
import tempfile

import yaml

from . import docker
from .manifest import HardwareTarget, ModelManifest


def start_stack(root: Path) -> None:
    docker.compose_file(
        root / "monitoring/compose.yaml",
        ["up", "-d", "--wait"],
        repository=root,
        project="inferpack-monitoring",
    )


def register_model(
    root: Path,
    manifest: ModelManifest,
    engine: str,
    target: HardwareTarget,
    environment: str,
) -> None:
    # Compose's container publishers include .env and shell port overrides.
    # Its ownership check prevents registering a different checkout's service.
    containers = docker.compose_ps(target)
    publishers = [
        publisher
        for container in containers if container["Service"] == engine
        for publisher in container.get("Publishers") or []
        if publisher.get("Protocol") == "tcp" and publisher.get("PublishedPort")
    ]
    try:
        port = docker.published_port(target, engine, containers=containers)
    except docker.DockerError as exc:
        raise RuntimeError(f"Cannot register monitoring: {exc}") from exc
    if not any(publisher.get("URL") in {"", "0.0.0.0", "::", None}
               for publisher in publishers):
        raise RuntimeError(
            "Cannot register monitoring: the model port must be published on "
            "all host interfaces so Prometheus can reach the Docker host gateway."
        )
    endpoint = f"host.docker.internal:{port}"
    labels = {
        "environment": environment,
        "model": manifest.identifier,
        "engine": engine,
        "hardware": target.name,
    }
    directory = root / "monitoring/prometheus/targets"
    directory.mkdir(parents=True, exist_ok=True)
    registry = directory / "local-auto.yml"
    # Serialize simultaneous registrations and publish the full file atomically;
    # Prometheus must never observe partially written YAML or duplicate endpoints.
    with (directory / ".local-auto.lock").open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        for path in sorted(directory.glob("*.yml")):
            if path != registry and any(
                endpoint in group["targets"] for group in _read_targets(path)
            ):
                raise RuntimeError(
                    f"Monitoring endpoint {endpoint} is already configured in {path}. "
                    "Remove that manual entry and rerun make start to use automatic labels."
                )
        groups = _read_targets(registry) if registry.exists() else []
        updated = []
        for group in groups:
            # A pack moving ports or changing environment replaces its old entry.
            if all(group.get("labels", {}).get(key) == labels[key]
                   for key in ("model", "engine", "hardware")):
                continue
            remaining = [value for value in group["targets"] if value != endpoint]
            if remaining:
                updated.append({**group, "targets": remaining})
        updated.append({"targets": [endpoint], "labels": labels})
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w", dir=directory, prefix=".local-auto-", suffix=".tmp",
                encoding="utf-8", delete=False,
            ) as stream:
                temporary = Path(stream.name)
                stream.write("# Generated by infer start; manual remote targets belong in separate files.\n")
                yaml.safe_dump(updated, stream, sort_keys=False)
            # NamedTemporaryFile defaults to 0600; Prometheus runs as another UID.
            temporary.chmod(0o644)
            os.replace(temporary, registry)
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)
    print(
        f"[ok] Prometheus target: {endpoint} "
        f"({environment} / {manifest.identifier} / {engine} / {target.name}). "
        "Collection begins when the model exposes /metrics; discovery refreshes every 15s."
    )


def _read_targets(path: Path) -> list[dict]:
    try:
        groups = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    except yaml.YAMLError as exc:
        raise RuntimeError(f"Invalid Prometheus target YAML in {path}") from exc
    if not isinstance(groups, list) or any(
        not isinstance(group, dict)
        or not isinstance(group.get("targets"), list)
        or any(not isinstance(value, str) for value in group["targets"])
        or not isinstance(group.get("labels", {}), dict)
        for group in groups
    ):
        raise RuntimeError(f"Invalid Prometheus target groups in {path}")
    return groups
